import fs from 'node:fs';
const origin=process.argv[2]||'http://127.0.0.1:3010';const live=origin.startsWith('https://');
const state=JSON.parse(fs.readFileSync('data/waug/editorial.json','utf8'));const articles=live?state.articles.filter(a=>a.publishedAt):state.articles;
const queue=[...articles],results=[];
await Promise.all(Array.from({length:3},async()=>{while(queue.length){const a=queue.shift(),url=`${origin}/tickets/${a.slug}`;try{const r=await fetch(url+(live?'?verify='+Date.now():''),{signal:AbortSignal.timeout(60000)}),h=await r.text();
const tags=[...h.matchAll(/<(?:meta|link|img|a)\b[^>]*>/g)].map(m=>m[0]);const attr=(t,n)=>t.match(new RegExp(`(?:^|\\s)${n}="([^"]*)"`))?.[1];const og=tags.find(t=>attr(t,'property')==='og:image'),canonical=tags.find(t=>attr(t,'rel')==='canonical');const image=attr(og||'','content'),hero=tags.find(t=>t.startsWith('<img')&&attr(t,'src')===image);const affiliate=tags.filter(t=>t.startsWith('<a')&&/^https:\/\/www.waug.com\/r\//.test(attr(t,'href')||''));
const errors=[];if(r.status!==200)errors.push('HTTP '+r.status);if(!image?.endsWith(a.thumbnail.url.split('/').pop())||!hero)errors.push('hero/OG mismatch');if(attr(canonical||'','href')!==`https://mwohaji.kr/tickets/${a.slug}`)errors.push('canonical');if(affiliate.length!==a.productIds.length||affiliate.some(t=>!attr(t,'rel')?.includes('sponsored')))errors.push('affiliate links');if(!h.includes('와그 파트너스 활동의 일환'))errors.push('disclosure');if(a.thumbnail.kind==='ai-generated'&&!h.includes('실제 시설 촬영 사진이 아닙니다'))errors.push('AI disclosure');if(h.includes('3ha.in/r/'))errors.push('old stay promo');if(!h.includes('"@type":"Article"'))errors.push('Article schema');results.push({slug:a.slug,url,status:r.status,image,affiliateCount:affiliate.length,errors,checkedAt:new Date().toISOString()});
}catch(e){results.push({slug:a.slug,errors:[e.message]});}}}));
const out=`data/waug/${live?'live':'preview'}-page-check.json`;fs.writeFileSync(out,JSON.stringify(results,null,2)+'\n');console.log({total:results.length,passed:results.filter(x=>!x.errors.length).length,failed:results.filter(x=>x.errors.length)});if(results.some(x=>x.errors.length))process.exitCode=1;
