import Link from "next/link";
import type { Metadata } from "next";
import { getAllEvents } from "@/lib/data";
import { CHUSEOK_START, CHUSEOK_END } from "@/lib/chuseok";
import { CHUSEOK_AREAS, CHUSEOK_TOPICS, chuseokSeoSlugs } from "@/lib/chuseokSeo";

type Props={params:{slug:string}};
const areaMap=Object.fromEntries(CHUSEOK_AREAS.map(([slug,name,detail])=>[slug,{name,detail}]));
const topicMap=Object.fromEntries(CHUSEOK_TOPICS);
const year="2026";
export function generateStaticParams(){return chuseokSeoSlugs.map(slug=>({slug}));}
export function generateMetadata({params}:Props):Metadata{const area=areaMap[params.slug];const title=area?`${year} ${area.name} 추석 가볼만한곳`: `${year} 추석 ${topicMap[params.slug]||"가볼만한곳"}`;return {title,description:`${title}. 실제 진행 일정이 확인된 행사와 문화공간을 조건별로 찾아보세요.`,alternates:{canonical:`/chuseok/${params.slug}`}};}
export default function ChuseokSeoPage({params}:Props){const area=areaMap[params.slug];const topic=topicMap[params.slug];const events=getAllEvents().filter(e=>e.endDate>=CHUSEOK_START&&e.startDate<=CHUSEOK_END).filter(e=>area?e.area===area.name:topic==="무료행사"?e.priceType==="free"||e.priceType==="free_estimated":topic==="아이와 가볼만한곳"?e.audiences?.includes("kids"):topic==="전통체험"?/전통|한옥|민속|궁|역사|체험/.test(`${e.title} ${e.contents}`):topic==="추석 연휴 축제"?/축제|페스티벌|마당/.test(`${e.title} ${e.contents}`):topic==="실내 가볼만한곳"?/전시|박물관|미술관|공연/.test(`${e.title} ${e.contents}`):/공연|전시|야간/.test(`${e.title} ${e.contents}`)).slice(0,18);const h1=area?`${year} ${area.name} 추석 가볼만한곳`:`${year} 추석 ${topic}`;const intro=area?`${area.name}은 ${area.detail}입니다. 추석 연휴에는 이동 시간과 운영 일정을 먼저 확인하면 가족, 부모님, 연인과의 일정을 더 편하게 정할 수 있습니다. 아래 목록은 연휴 기간과 겹치는 실제 문화행사 데이터를 바탕으로 정리했습니다. 행사별 날짜와 장소, 무료 여부를 확인하고 원하는 조건은 추석 특집관에서 다시 좁혀보세요.`:`추석 연휴에 ${topic}을 찾을 때는 행사 날짜와 장소, 동행자에게 맞는지부터 확인하는 것이 좋습니다. 아래에는 연휴 일정과 겹치는 실제 행사만 모았습니다. 무료 여부와 전통문화·아이 동반 적합 여부는 상세 안내를 확인하고, 더 세밀한 지역·날짜 조건은 추석 특집관 필터에서 고를 수 있습니다.`;return <main className="mx-auto max-w-[1180px] px-5 py-9 sm:px-6"><nav className="text-xs text-ink-faint"><Link href="/chuseok">추석 특집관</Link> / {h1}</nav><h1 className="mt-4 text-3xl font-black text-ink">{h1}</h1><p className="mt-4 max-w-3xl text-[15px] leading-8 text-ink-soft">{intro}</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{events.map(e=><Link key={e.id} href={`/event/${e.id}`} className="overflow-hidden rounded-xl border border-line bg-white"><div className="aspect-[4/3] bg-tint">{e.imgUrl&&<img src={e.imgUrl} alt="" className="h-full w-full object-cover"/>}</div><div className="p-3"><h2 className="line-clamp-2 text-sm font-black text-ink">{e.title}</h2><p className="mt-2 text-xs text-ink-soft">{e.area} · {e.startDate.slice(4,6)}.{e.startDate.slice(6)}–{e.endDate.slice(4,6)}.{e.endDate.slice(6)}</p></div></Link>)}</div><section className="mt-10 border-t border-line pt-6"><h2 className="text-xl font-black text-ink">함께 보는 추석 정보</h2><div className="mt-3 flex flex-wrap gap-3 text-sm font-bold text-free"><Link href="/chuseok">지역·날짜로 추석 행사 찾기</Link>{CHUSEOK_TOPICS.slice(0,4).map(([slug,label])=><Link key={slug} href={`/chuseok/${slug}`}>추석 {label}</Link>)}</div><h2 className="mt-7 text-xl font-black text-ink">자주 묻는 질문</h2><p className="mt-3 text-sm leading-6 text-ink-soft">행사 운영 여부와 입장 조건은 주최 기관의 상세 안내가 가장 정확합니다. 추석 당일 운영이 명시되지 않은 장소는 방문 전 공식 안내를 확인해 주세요.</p></section></main>;}
