import Link from "next/link";
import type { Metadata } from "next";
import { getAllPlaces } from "@/lib/tour";
import { getAllCourses } from "@/lib/courses";
import { getAllRestaurants } from "@/lib/food";
import { CHUSEOK_AREAS, CHUSEOK_TOPICS, chuseokSeoSlugs } from "@/lib/chuseokSeo";

type Props={params:Promise<{slug:string}>};
const areaMap=Object.fromEntries(CHUSEOK_AREAS.map(([slug,name,detail])=>[slug,{name,detail}]));
const topicMap=Object.fromEntries(CHUSEOK_TOPICS);
const year="2026";
export function generateStaticParams(){return chuseokSeoSlugs.map(slug=>({slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const area=areaMap[slug];const title=area?`${year} ${area.name} 추석 가볼만한곳`: `${year} 추석 ${topicMap[slug]||"가볼만한곳"}`;return {title,description:`${title}. 기존 나들이, 여행코스, 맛집 콘텐츠로 추석 연휴 하루를 계획해 보세요.`,alternates:{canonical:`/chuseok/${slug}`}};}
export default async function ChuseokSeoPage({params}:Props){const {slug}=await params;const area=areaMap[slug];const topic=topicMap[slug];const areaName=area?.name;const placeItems=getAllPlaces().filter(x=>x.image&&(!areaName||x.area===areaName)).filter(x=>topic!=="아이와 가볼만한곳"||x.isKid).slice(0,12).map(x=>({id:`place-${x.id}`,title:x.title,area:x.area,image:x.image,href:`/places/spot/${x.id}`,label:"나들이"}));const courseItems=getAllCourses().filter(x=>x.image&&(!areaName||x.area===areaName)).filter(x=>topic!=="아이와 가볼만한곳"||(x.themes||[]).includes("가족체험")).slice(0,6).map(x=>({id:`course-${x.id}`,title:x.title,area:x.area,image:x.image,href:`/course/c/${x.id}`,label:"여행코스"}));const foodItems=getAllRestaurants().filter(x=>x.image&&(!areaName||x.area===areaName)).slice(0,4).map(x=>({id:`food-${x.id}`,title:x.title,area:x.area,image:x.image,href:`/food/spot/${x.id}`,label:"맛집탐방"}));const items=[...placeItems,...courseItems,...foodItems].slice(0,18);const h1=area?`${year} ${area.name} 추석 가볼만한곳`:`${year} 추석 ${topic}`;const intro=area?`${area.name}은 ${area.detail} 추석 연휴에는 한 곳을 오래 보기보다 산책할 곳과 식사, 가까운 여행지를 함께 묶어 동선을 가볍게 잡는 편이 좋습니다. 아래에는 이 지역에서 이미 소개한 실제 나들이, 여행코스, 맛집 콘텐츠를 모았습니다. 각 상세 글의 위치와 이용 안내를 확인해 무리 없는 하루 계획을 세워보세요.`:`추석 연휴에 ${topic}을 찾을 때는 특별행사 여부만 보기보다, 이동이 편한 실제 나들이와 여행코스를 먼저 고르는 편이 좋습니다. 아래 콘텐츠는 기존 홈페이지에서 소개한 장소를 바탕으로 정리했습니다. 상세페이지의 위치와 안내를 확인하고 동행자에게 맞는 하루 동선을 골라보세요.`;return <main className="mx-auto max-w-[1180px] px-5 py-9 sm:px-6"><nav className="text-xs text-ink-faint"><Link href="/chuseok">추석 특집관</Link> / {h1}</nav><h1 className="mt-4 text-3xl font-black text-ink">{h1}</h1><p className="mt-4 max-w-3xl text-[15px] leading-8 text-ink-soft">{intro}</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{items.map(x=><Link key={x.id} href={x.href} className="overflow-hidden rounded-xl border border-line bg-white"><div className="aspect-[4/3] bg-tint">{x.image&&<img src={x.image} alt="" className="h-full w-full object-cover"/>}</div><div className="p-3"><span className="text-[11px] font-bold text-free">{x.label}</span><h2 className="mt-1 line-clamp-2 text-sm font-black text-ink">{x.title}</h2><p className="mt-2 text-xs text-ink-soft">{x.area}</p></div></Link>)}</div><section className="mt-10 border-t border-line pt-6"><h2 className="text-xl font-black text-ink">함께 보는 추석 정보</h2><div className="mt-3 flex flex-wrap gap-3 text-sm font-bold text-free"><Link href="/chuseok">지역과 동행으로 추천 보기</Link>{CHUSEOK_TOPICS.slice(0,4).map(([slug,label])=><Link key={slug} href={`/chuseok/${slug}`}>추석 {label}</Link>)}</div><h2 className="mt-7 text-xl font-black text-ink">자주 묻는 질문</h2><p className="mt-3 text-sm leading-6 text-ink-soft">관광지와 식당의 추석 연휴 운영 여부는 장소마다 다릅니다. 상세페이지의 공식 안내와 연락처를 확인한 뒤 방문해 주세요.</p></section></main>;}
