import test from 'node:test';
import assert from 'node:assert/strict';
import {sharedProductRequest,validateBudget} from './github-budget.mjs';
function fake(saved){let rev=0,now=0,state=saved||{version:1,revision:'initial',cap:10,window:60000,interval:6100,nextAt:0,events:[],lock:null,cache:{}};const starts=[];return {starts,get state(){return state;},get now(){return now;},advance(ms){now+=ms;},sleep:async ms=>{now+=ms;},backend:{read:async()=>({state:structuredClone(state),sha:String(rev),now}),write:async(s,next)=>{if(s.sha!==String(rev))return false;state=structuredClone(next);state.revision=String(++rev);return true;}},run:async()=>{starts.push(now);return Response.json({ok:true});}};}
const options=b=>({backend:b.backend,sleep:b.sleep,maxWait:10000000});
function withinCap(b){for(const t of b.starts)assert(b.starts.filter(x=>x>t-60000&&x<=t).length<=10);}
test('concurrent CAS contenders cannot exceed account-wide rolling quota',async()=>{const b=fake();await Promise.all(Array.from({length:20},(_,i)=>sharedProductRequest('key'+i,b.run,options(b))));assert.equal(b.starts.length,20);withinCap(b);for(let i=1;i<b.starts.length;i++)assert(b.starts[i]-b.starts[i-1]>=6100);});
test('cached products need no new API request, including another caller',async()=>{const b=fake();await sharedProductRequest('same',b.run,options(b));const r=await sharedProductRequest('same',b.run,options(b));assert.equal(b.starts.length,1);assert.equal(r.headers.get('X-Prep-Cache'),'hit');});
test('failures count; retries use a new shared reservation',async()=>{const b=fake();for(let i=0;i<20;i++)await sharedProductRequest('failed',async()=>{b.starts.push(b.now);return new Response('',{status:500});},options(b));assert.equal(b.starts.length,20);withinCap(b);});
test('server restart retains lock after ambiguous connection loss',async()=>{const b=fake();await assert.rejects(sharedProductRequest('a',async()=>{throw Error('network');},options(b)));const next=fake(structuredClone(b.state));await assert.rejects(sharedProductRequest('b',next.run,{...options(next),maxWait:5000}));assert.equal(next.starts.length,0);});
test('429 cooldown is persisted and not automatically retried',async()=>{const b=fake();await assert.rejects(sharedProductRequest('a',async()=>new Response('',{status:429,headers:{'retry-after':'180'}}),options(b)));await sharedProductRequest('b',b.run,options(b));assert(b.starts[0]>=182000);});
test('ten product units allowed, eleventh waits through the window',async()=>{const b=fake();await sharedProductRequest('a',b.run,{...options(b),count:10});await sharedProductRequest('b',b.run,options(b));assert(b.starts[1]>=62000);await assert.rejects(sharedProductRequest('c',b.run,{...options(b),count:11}));});
test('state corruption, stale CAS, and backend outage fail closed',async()=>{assert.throws(()=>validateBudget({}));let calls=0;await assert.rejects(sharedProductRequest('a',async()=>{calls++;},{backend:{read:async()=>{throw Error('offline');}}}));assert.equal(calls,0);const b=fake();b.backend.write=async()=>false;await assert.rejects(sharedProductRequest('x',b.run,{...options(b),maxWait:1000}));assert.equal(b.starts.length,0);});
test('completion-time accounting and stricter account settings survive restart',async()=>{const b=fake();await sharedProductRequest('a',async()=>{b.advance(100000);return new Response('');},{...options(b),count:10});const next=fake(structuredClone(b.state));await sharedProductRequest('b',next.run,options(next));assert(next.starts[0]>=162000);const strict=fake({...b.state,lock:null,events:[],cache:{},nextAt:0,cap:1,window:120000,interval:15000});await sharedProductRequest('c',strict.run,options(strict));await sharedProductRequest('d',strict.run,options(strict));assert(strict.starts[1]>=122000);});
