import test from 'node:test';
import assert from 'node:assert/strict';
import {ACQUIRE,RELEASE,limitedRequest,retryDelay} from './limiter.mjs';
// Fake Redis models one atomic command and one durable shared primary; no paid API.
function backend(saved){let now=0;let state=saved||{events:[],cap:10,window:60000,interval:6100,nextAt:0};const starts=[];
 const command=async([,script,,key,token,arg])=>{if(!state)return [-1,0];if(script===RELEASE){if(state.lock!==token)return -1;for(const e of state.events)if(e.id===token)e.at=now;state.nextAt=now+Math.max(6100,state.interval,arg);delete state.lock;return 1;}assert.equal(script,ACQUIRE);if(state.lock)return [0,1000];if(now<state.nextAt)return [0,state.nextAt-now];state.events=state.events.filter(e=>e.at>now-state.window);if(state.events.reduce((s,e)=>s+e.count,0)+arg>Math.min(9,state.cap))return [0,state.events[0].at+state.window-now+1];state.lock=token;state.events.push({id:token,at:now,count:arg});return [1,0];};
 return {command,starts,get now(){return now;},set now(v){now=v;},get state(){return state;},lose(){state=null;},sleep:async ms=>{now+=ms;},run:async()=>{starts.push(now);return new Response('ok');}};
}
const opts=b=>({command:b.command,key:'same-account',sleep:b.sleep,maxWait:1000000});
test('10th request waits: every rolling 60s has <=9 calls and products',async()=>{const b=backend();for(let i=0;i<40;i++)await limitedRequest(b.run,opts(b));for(const t of b.starts)assert(b.starts.filter(x=>x>t-60000&&x<=t).length<=9);assert(b.starts[9]>=60000);assert(b.starts[10]>=61000);});
test('multiple concurrent callers use one central budget',async()=>{const b=backend();await Promise.all(Array.from({length:25},()=>limitedRequest(b.run,opts(b))));for(const t of b.starts)assert(b.starts.filter(x=>x>t-60000&&x<=t).length<=9);});
test('failed response and retries still consume quota',async()=>{const b=backend();for(let i=0;i<12;i++)await limitedRequest(async()=>{b.starts.push(b.now);return new Response('',{status:500});},opts(b));assert.equal(b.starts.length,12);assert(b.starts[10]>=61000);});
test('HTTP 429 Retry-After is shared by the next server',async()=>{const b=backend();await limitedRequest(async()=>new Response('',{status:429,headers:{'retry-after':'120'}}),opts(b));assert.equal(b.state.nextAt,120000);await limitedRequest(b.run,opts(b));assert(b.starts[0]>=120000);assert.equal(retryDelay('Sun, 13 Sep 2026 10:02:00 GMT',Date.parse('2026-09-13T10:00:00Z')),120000);});
test('server restart preserves budget and a crashed owner cannot be bypassed',async()=>{const b=backend();await limitedRequest(b.run,opts(b));const restarted=backend(JSON.parse(JSON.stringify(b.state)));await limitedRequest(restarted.run,opts(restarted));assert(restarted.starts[0]>=6100);await assert.rejects(limitedRequest(async()=>{throw Error('connection ambiguous');},opts(restarted)));assert(restarted.state.lock);const again=backend(JSON.parse(JSON.stringify(restarted.state)));await assert.rejects(limitedRequest(again.run,{...opts(again),maxWait:2000}));assert.equal(again.starts.length,0);});
test('missing backend state fails closed; multi-product requests count every product',async()=>{const b=backend();await limitedRequest(b.run,{...opts(b),count:9});await limitedRequest(b.run,opts(b));assert(b.starts[1]>60000);b.lose();await assert.rejects(limitedRequest(b.run,opts(b)));await assert.rejects(limitedRequest(b.run,{...opts(b),count:11}));});
test('stricter account window and gap win',async()=>{const b=backend({events:[],cap:2,window:120000,interval:15000,nextAt:0});for(let i=0;i<3;i++)await limitedRequest(b.run,opts(b));assert(b.starts[1]>=15000);assert(b.starts[2]>120000);});
test('central transport failure never reaches Coupang',async()=>{let called=false;await assert.rejects(limitedRequest(async()=>{called=true;return new Response('');},{key:'x',command:async()=>{throw Error('Redis unavailable');}}));assert.equal(called,false);});


test('delayed batches are charged through completion, not only reservation time',async()=>{const b=backend();await limitedRequest(async()=>{b.now=100000;b.starts.push(b.now);return new Response('ok');},{...opts(b),count:9});await limitedRequest(b.run,opts(b));assert(b.starts[1]>160000);});
