"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { SAVED_KEY, parseSaved, type TripStop } from "@/lib/planner";
import HomeRegionPicker from './HomeRegionPicker';
import HomeNearbyButton from './HomeNearbyButton';
import GamePromoBanner from './GamePromoBanner';
import TossAffiliate from './TossAffiliate';
import type {TossFeed} from '@/lib/sharelink';
import { useRenderDay } from "./RenderDate";
import { formatKoreanDate, weekendRangeYmd } from "@/lib/dates";

export type HomeItem = { id: string; href: string; title: string; meta: string; image: string; badge: string; area?: string; start?: string; end?: string };
type Props = { regional: Record<string, HomeItem[]>; eventItems: HomeItem[]; freeItems: HomeItem[]; kidItems: HomeItem[]; dateItems: HomeItem[]; campItems: HomeItem[]; courseItems: HomeItem[]; seasonItems: HomeItem[]; prepItems: HomeItem[]; placeItems: HomeItem[]; newItems: HomeItem[]; regions: { name: string; href: string }[]; siteName: string };
const savedKey = SAVED_KEY;
const regionalAreas: Record<string, string[]> = { 충청: ["충북", "충남", "대전", "세종"], 경상: ["경북", "경남", "부산", "대구", "울산"], 전라: ["전북", "전남", "광주"], 전국: [] };
const categories = [["🎭", "문화행사", "/events"], ["🌿", "나들이", "/places"], ["🗺️", "여행코스", "/course"], ["🚌", "시티투어", "/city-tour"], ["⛺", "캠핑", "/camping"], ["🍽️", "맛집탐방", "/food"], ["🐾", "반려동물 여행", "/pet-travel"], ["👨‍👩‍👧", "아이와 함께", "/kids"], ["💛", "데이트", "/date"], ["🍂", "가을나들이", "/season"], ["🧺", "준비 가이드", "/weekend-prep"]];

export default function HomeExplorer({ regional, eventItems, freeItems, kidItems, dateItems, campItems, courseItems, seasonItems, prepItems, placeItems, newItems, regions, siteName, tossFeed }: Props & {tossFeed:TossFeed}) {
  const day = useRenderDay();
  const weekend = weekendRangeYmd(day);
  const currentEventItems = eventItems.filter((item) => item.start && item.end && item.start <= weekend.end && item.end >= weekend.start);
  const currentFreeItems = freeItems.filter((item) => !item.end || item.end >= day);
  const weekendLabel = weekend.start === weekend.end ? formatKoreanDate(weekend.start) : `${formatKoreanDate(weekend.start)} ~ ${formatKoreanDate(weekend.end)}`;
  const router = useRouter(); const [query, setQuery] = useState(""); const [region, setRegion] = useState("서울"); const [saved, setSaved] = useState<string[]>([]);
  const regionLinks = regions.filter((item) => (regionalAreas[region] || [region]).includes(item.name));
  useEffect(() => { const sync = () => { try { setSaved(parseSaved(localStorage.getItem(savedKey)).filter(t => t.stops.length === 1).map(t => t.stops[0].href)); } catch {} }; sync(); window.addEventListener("trip-saved", sync); window.addEventListener("storage", sync); return () => { window.removeEventListener("trip-saved", sync); window.removeEventListener("storage", sync); }; }, []);
  const submit = (event: FormEvent) => { event.preventDefault(); if (query.trim()) router.push(`/search?q=${encodeURIComponent(query.trim())}`); };
  const toggleSave = (item: HomeItem) => { try { const old = parseSaved(localStorage.getItem(savedKey)); const exists = old.some(t => t.stops.length === 1 && t.stops[0].href === item.href); if (!exists && old.length >= 100) { alert("보관함은 최대 100개까지 저장할 수 있어요."); return; } const kind: TripStop["kind"] = item.id.startsWith("event-") ? "event" : item.id.startsWith("camp-") ? "camp" : item.id.startsWith("course-") || item.id.startsWith("date-") ? "course" : "place"; const next = exists ? old.filter(t => !(t.stops.length === 1 && t.stops[0].href === item.href)) : [{ id: item.id, title: item.title, stops: [{ id: item.id, title: item.title, href: item.href, area: item.area || "", image: item.image, start: item.start, end: item.end, kind }] }, ...old]; localStorage.setItem(savedKey, JSON.stringify(next)); window.dispatchEvent(new Event("trip-saved")); } catch { alert("브라우저에서 저장을 허용한 뒤 다시 시도해 주세요."); } };
  return <div className="bg-white pb-12">
    <section className="mx-auto w-full max-w-[1120px] px-4 pb-3 pt-2 sm:px-6" aria-label="여행 검색"><h1 className="sr-only">이번 주말, 어디 갈까요?</h1><form onSubmit={submit} className="relative" role="search"><span className="pointer-events-none absolute left-4 top-3 text-xl" aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="지역·축제·여행지를 검색하세요" aria-label="지역, 축제, 아이와 갈 곳 검색" className="h-12 w-full rounded-full border-2 border-[#102344] bg-white pl-11 pr-20 text-[15px] outline-none focus:border-brandblue" /><button type="submit" className="absolute right-2 top-1.5 h-9 rounded-full px-4 text-sm font-bold text-[#102344]">검색</button></form></section>
    <TossAffiliate initial={tossFeed} position="top" display="banner" />
    <section className="mx-auto w-full max-w-[1120px] px-4 py-4 sm:px-6 lg:px-8" aria-label="여행 카테고리"><div className="grid grid-cols-5 gap-x-1 gap-y-3 sm:grid-cols-10">{categories.filter((item)=>item[2]!=='/pet-travel').map(([icon,label,href],index)=><Link key={label} href={href} prefetch={index<5?undefined:false} className="flex min-w-0 flex-col items-center gap-1 text-center text-[11px] font-bold text-ink sm:text-[12px]"><span className="flex h-11 w-11 items-center justify-center text-[29px] sm:h-12 sm:w-12">{icon}</span><span className="break-keep leading-4">{label}</span></Link>)}</div></section>
    <section className="mx-auto flex w-full max-w-[1120px] items-center gap-2 border-y border-slate-100 px-4 py-2 sm:px-6 lg:px-8"><HomeNearbyButton/><Link href="/weekend" className="rounded-full bg-[#f3f6fa] px-3 py-2 text-xs font-bold">이번 주말</Link><Link href="/plan" className="rounded-full bg-[#f3f6fa] px-3 py-2 text-xs font-bold">맞춤 추천</Link><Link href="/saved" className="ml-auto text-xs font-bold">♡ 보관함</Link></section>
    <Section title="지역별 나들이" href="/places" description="선택한 지역의 행사·장소·여행코스를 함께 비교해 보세요."><div className="-mx-5 mb-4 flex gap-2 overflow-x-auto px-5 pb-1 sm:mx-0 sm:px-0">{Object.keys(regional).map((name) => <button key={name} onClick={() => setRegion(name)} aria-pressed={region === name} className={`min-h-11 shrink-0 rounded-full px-3.5 py-2 text-[13px] font-bold transition ${region === name ? "bg-[#102344] text-white" : "bg-[#f4f6f8] text-ink-soft hover:bg-slate-200"}`}>{name}</button>)}</div><p className="mb-3 text-[14px] font-bold text-ink" aria-live="polite">{region}에서 가볼 만한 곳</p><Rail items={(regional[region] || []).filter((item) => !item.end || item.end >= day)} saved={saved} toggleSave={toggleSave} /><nav className="mt-3 flex flex-wrap gap-x-4 gap-y-1" aria-label={`${region} 지역 전체 둘러보기`}>{regionLinks.map((item) => <Link key={item.name} href={item.href} prefetch={false} className="inline-flex min-h-11 items-center text-[13px] font-bold text-brandblue">{item.name} 전체 둘러보기 →</Link>)}{region === "전국" && <Link href="#home-region-title" className="inline-flex min-h-11 items-center text-[13px] font-bold text-brandblue">방문할 지역 고르기 ↓</Link>}</nav></Section>

    <TossAffiliate initial={tossFeed} position="top" display="rail" />
    <TossAffiliate initial={tossFeed} position="top" compact collection="stay" />
    {kidItems.length > 0 && <Section title="아이와 어디 가지?" href="/kids"><Rail items={kidItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {dateItems.length > 0 && <Section title="데이트·드라이브" href="/date" description="카페·산책·식사를 묶은 방문 후보예요. 상세에서 방문 순서와 실제 이동 경로를 확인하세요."><Rail items={dateItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {currentEventItems.length > 0 && <Section title="이번 주말 행사" href="/weekend" description={`${weekendLabel}에 기간이 겹치는 행사예요. 회차·운영일·예약은 상세에서 확인하세요.`}><Rail items={currentEventItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {courseItems.length > 0 && <Section title="여행코스" href="/course"><Rail items={courseItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {campItems.length > 0 && <Section title="캠핑" href="/camping"><Rail items={campItems} saved={saved} toggleSave={toggleSave} /></Section>}
    <TossAffiliate initial={tossFeed} position="top" compact collection="travel" />
    {seasonItems.length > 0 && <Section title="계절별 추천" href="/season"><Rail items={seasonItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {prepItems.length > 0 && <Section title="준비 가이드" href="/weekend-prep"><Rail items={prepItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {placeItems.length > 0 && <Section title="대표 장소" href="/places"><Rail items={placeItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {newItems.length > 0 && <Section title="새로 둘러볼 콘텐츠" href="/places"><Rail items={newItems} saved={saved} toggleSave={toggleSave} /></Section>}
    {currentFreeItems.length > 0 && <Section title="가볼 만한 무료행사" href="/free" description="무료와 일부 조건에서 무료인 문화행사를 구분해 보여드려요."><Rail items={currentFreeItems} saved={saved} toggleSave={toggleSave} /></Section>}
    <HomeRegionPicker regions={regions}/>
    <GamePromoBanner />
  </div>;
}
function QuickLink({ icon, title, text, href }: { icon: string; title: string; text: string; href: string }) { return <Link href={href} className="min-w-0 rounded-2xl bg-[#f5f7fa] p-3.5 transition hover:bg-[#eaf2ff] sm:p-5"><span className="text-[21px]">{icon}</span><strong className="mt-2 block break-keep text-[13px] leading-5 text-ink sm:text-[16px]">{title}</strong><span className="mt-0.5 block break-keep text-[10px] leading-4 text-ink-faint sm:text-[12px]">{text}</span></Link>; }
function Section({ title, href, description, children }: { title: string; href: string; description?: string; children: React.ReactNode }) { return <section className="mx-auto w-full max-w-[1120px] px-4 pt-6 sm:px-6 sm:pt-9 lg:px-8"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-[20px] font-black tracking-tight text-ink sm:text-[24px]">{title}</h2>{description && <p className="mt-1 max-w-2xl text-[13px] leading-5 text-ink-soft">{description}</p>}</div><Link href={href} className="shrink-0 pt-1 text-[13px] font-bold text-ink-soft hover:text-brandblue">더보기 ›</Link></div>{children}</section>; }
function Rail({ items, saved, toggleSave }: { items: HomeItem[]; saved: string[]; toggleSave: (item: HomeItem) => void }) { if (!items.length) return <p className="rounded-xl bg-[#f5f7fa] px-4 py-8 text-center text-[13px] text-ink-faint">추천할 콘텐츠를 준비하고 있어요.</p>; return <div className="-mx-5 flex snap-x gap-3 overflow-x-auto px-5 pb-2 sm:mx-0 sm:px-0">{items.slice(0, 8).map((item, index) => <article key={item.id} className="group relative w-[176px] shrink-0 snap-start overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-lg sm:w-[220px]"><Link href={item.href} prefetch={index === 0 ? undefined : false} className="block"><div className="relative aspect-[1.45/1] bg-slate-100">{item.image ? <img src={item.image} alt="" loading={index < 2 ? "eager" : "lazy"} className="absolute inset-0 h-full w-full object-cover" /> : null}<span className="absolute bottom-2 left-2 max-w-[85%] truncate rounded-md bg-black/55 px-1.5 py-0.5 text-[10px] font-bold text-white">{item.badge}</span></div><div className="p-3"><h3 className="line-clamp-2 min-h-[38px] text-[14px] font-black leading-snug text-ink">{item.title}</h3><p className="mt-1 line-clamp-1 text-[12px] text-ink-faint">{item.meta}</p></div></Link><button onClick={() => toggleSave(item)} aria-label={`${item.title} ${saved.includes(item.href) ? "보관 취소" : "보관"}`} className={`absolute right-2 top-2 flex h-11 w-11 items-center justify-center rounded-full text-[18px] ${saved.includes(item.href) ? "bg-white text-rose-500" : "bg-black/35 text-white"}`}>{saved.includes(item.href) ? "♥" : "♡"}</button></article>)}</div>; }
