"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { SAVED_KEY, parseSaved, type TripStop } from "@/lib/planner";
import HomeRegionPicker from './HomeRegionPicker';

export type HomeItem = { id: string; href: string; title: string; meta: string; image: string; badge: string; area?: string; start?: string; end?: string };
type Props = { regional: Record<string, HomeItem[]>; todayItems: HomeItem[]; freeItems: HomeItem[]; kidItems: HomeItem[]; dateItems: HomeItem[]; courseItems: HomeItem[]; regions: { name: string; href: string }[]; siteName: string };
const savedKey = SAVED_KEY;
const categories = [["🎭", "문화행사", "/events"], ["🌿", "나들이", "/places"], ["🗺️", "여행코스", "/course"], ["🚌", "시티투어", "/city-tour"], ["⛺", "캠핑", "/camping"], ["🍽️", "맛집탐방", "/food"], ["🐾", "반려동물 여행", "/pet-travel"], ["👨‍👩‍👧", "아이와 함께", "/kids"], ["💛", "데이트", "/date"], ["🍂", "가을나들이", "/season"]];

export default function HomeExplorer({ regional, todayItems, freeItems, kidItems, dateItems, courseItems, regions, siteName }: Props) {
  const router = useRouter(); const [query, setQuery] = useState(""); const [region, setRegion] = useState("서울"); const [saved, setSaved] = useState<string[]>([]);
  useEffect(() => { const sync = () => { try { setSaved(parseSaved(localStorage.getItem(savedKey)).filter(t => t.stops.length === 1).map(t => t.stops[0].href)); } catch {} }; sync(); window.addEventListener("trip-saved", sync); window.addEventListener("storage", sync); return () => { window.removeEventListener("trip-saved", sync); window.removeEventListener("storage", sync); }; }, []);
  const submit = (event: FormEvent) => { event.preventDefault(); if (query.trim()) router.push(`/search?q=${encodeURIComponent(query.trim())}`); };
  const toggleSave = (item: HomeItem) => { try { const old = parseSaved(localStorage.getItem(savedKey)); const exists = old.some(t => t.stops.length === 1 && t.stops[0].href === item.href); if (!exists && old.length >= 100) { alert("보관함은 최대 100개까지 저장할 수 있어요."); return; } const kind: TripStop["kind"] = item.id.startsWith("event-") ? "event" : item.id.startsWith("camp-") ? "camp" : item.id.startsWith("course-") || item.id.startsWith("date-") ? "course" : "place"; const next = exists ? old.filter(t => !(t.stops.length === 1 && t.stops[0].href === item.href)) : [{ id: item.id, title: item.title, stops: [{ id: item.id, title: item.title, href: item.href, area: item.area || "", image: item.image, start: item.start, end: item.end, kind }] }, ...old]; localStorage.setItem(savedKey, JSON.stringify(next)); window.dispatchEvent(new Event("trip-saved")); } catch { alert("브라우저에서 저장을 허용한 뒤 다시 시도해 주세요."); } };
  return <div className="bg-white pb-12">
    <section className="border-b border-slate-100 bg-[#f7faff]"><div className="mx-auto w-full max-w-[1120px] px-5 pb-7 pt-8 sm:px-6 sm:pb-10 sm:pt-12 lg:px-8"><p className="text-[13px] font-extrabold text-brandblue">{siteName}</p><h1 className="mt-2 text-[30px] font-black tracking-[-0.045em] text-[#102344] sm:text-[43px]">이번 주말, 어디 갈까요?</h1><p className="mt-2 text-[15px] font-medium text-ink-soft sm:text-[17px]">지역과 취향을 고르면, 갈 만한 곳을 바로 찾을 수 있어요.</p><form onSubmit={submit} className="relative mt-6 max-w-[680px]" role="search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="지역·축제·아이와 갈 곳 검색" aria-label="지역, 축제, 아이와 갈 곳 검색" className="h-14 w-full rounded-2xl border-0 bg-white pl-5 pr-24 text-[16px] font-medium text-ink shadow-[0_8px_24px_rgba(18,45,81,0.10)] outline-none ring-1 ring-slate-200 placeholder:text-ink-faint focus:ring-2 focus:ring-brandblue/35" /><button type="submit" className="absolute right-1.5 top-1.5 h-11 rounded-xl bg-[#102344] px-4 text-[14px] font-bold text-white">검색</button></form></div></section>
    <section className="mx-auto grid w-full max-w-[1120px] grid-cols-3 gap-2 px-5 pt-5 sm:gap-4 sm:px-6 sm:pt-8 lg:px-8"><QuickLink icon="🗓️" title="이번 주말" text="지금 열리는 행사" href="/weekend" /><QuickLink icon="✨" title="내 조건으로" text="지역·테마로 찾기" href="/plan" /><QuickLink icon="♡" title="보관함" text="찜한 곳 모아보기" href="/saved" /></section>
    <section className="mx-auto w-full max-w-[1120px] px-5 pt-8 sm:px-6 lg:px-8"><div className="grid grid-cols-6 gap-x-1 gap-y-4 sm:grid-cols-[repeat(11,minmax(0,1fr))] sm:gap-2">{categories.map(([icon, label, href]) => <Link key={label} href={href} prefetch={false} className="flex min-w-0 flex-col items-center gap-1.5 text-center text-[11px] font-bold text-ink-soft transition hover:text-brandblue sm:text-[12px]"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#f5f7fa] text-[18px] sm:h-11 sm:w-11">{icon}</span><span className="break-keep leading-4">{label}</span></Link>)}</div></section>
    <Section title="이번 주말 뭐하지?" href="/weekend" description="지역을 고르면 이번 주말에 갈 만한 곳이 바로 바뀝니다."><div className="-mx-5 mb-4 flex gap-2 overflow-x-auto px-5 pb-1 sm:mx-0 sm:px-0">{Object.keys(regional).map((name) => <button key={name} onClick={() => setRegion(name)} aria-pressed={region === name} className={`min-h-11 shrink-0 rounded-full px-3.5 py-2 text-[13px] font-bold transition ${region === name ? "bg-[#102344] text-white" : "bg-[#f4f6f8] text-ink-soft hover:bg-slate-200"}`}>{name}</button>)}</div><p className="mb-3 text-[14px] font-bold text-ink">이번 주말 {region}에서 뭐하지?</p><Rail items={regional[region] || []} saved={saved} toggleSave={toggleSave} /></Section>
    <Section title="오늘의 추천" href="/events" description="문화행사부터 나들이까지, 함께 둘러보기 좋은 곳을 골랐어요."><Rail items={todayItems} saved={saved} toggleSave={toggleSave} /></Section>
    <Section title="돈 적게 들고 즐기기" href="/free" description="무료·무료 추정·조건부 무료로 확인된 문화행사를 모았어요."><Rail items={freeItems} saved={saved} toggleSave={toggleSave} /></Section>
    <Section title="아이와 어디 가지?" href="/kids"><Rail items={kidItems} saved={saved} toggleSave={toggleSave} /></Section>
    <Section title="데이트·드라이브" href="/date" description="카페, 산책, 식사를 가까운 동선으로 묶은 반나절 코스예요."><Rail items={dateItems} saved={saved} toggleSave={toggleSave} /></Section>
    <Section title="하루 코스로 다녀오기" href="/course"><Rail items={courseItems} saved={saved} toggleSave={toggleSave} /></Section>
    <HomeRegionPicker regions={regions}/>
  </div>;
}
function QuickLink({ icon, title, text, href }: { icon: string; title: string; text: string; href: string }) { return <Link href={href} className="min-w-0 rounded-2xl bg-[#f5f7fa] p-3.5 transition hover:bg-[#eaf2ff] sm:p-5"><span className="text-[21px]">{icon}</span><strong className="mt-2 block truncate text-[14px] text-ink sm:text-[16px]">{title}</strong><span className="mt-0.5 block truncate text-[10px] text-ink-faint sm:text-[12px]">{text}</span></Link>; }
function Section({ title, href, description, children }: { title: string; href: string; description?: string; children: React.ReactNode }) { return <section className="mx-auto w-full max-w-[1120px] px-5 pt-10 sm:px-6 sm:pt-14 lg:px-8"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-[20px] font-black tracking-tight text-ink sm:text-[24px]">{title}</h2>{description && <p className="mt-1 max-w-2xl text-[13px] leading-5 text-ink-soft">{description}</p>}</div><Link href={href} className="shrink-0 pt-1 text-[13px] font-bold text-ink-soft hover:text-brandblue">더보기 ›</Link></div>{children}</section>; }
function Rail({ items, saved, toggleSave }: { items: HomeItem[]; saved: string[]; toggleSave: (item: HomeItem) => void }) { if (!items.length) return <p className="rounded-xl bg-[#f5f7fa] px-4 py-8 text-center text-[13px] text-ink-faint">추천할 콘텐츠를 준비하고 있어요.</p>; return <div className="-mx-5 flex snap-x gap-3 overflow-x-auto px-5 pb-2 sm:mx-0 sm:px-0">{items.slice(0, 8).map((item, index) => <article key={item.id} className="group relative w-[176px] shrink-0 snap-start overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-lg sm:w-[220px]"><Link href={item.href} prefetch={false} className="block"><div className="relative aspect-[1.45/1] bg-slate-100">{item.image ? <img src={item.image} alt="" loading={index < 2 ? "eager" : "lazy"} className="absolute inset-0 h-full w-full object-cover" /> : null}<span className="absolute bottom-2 left-2 max-w-[85%] truncate rounded-md bg-black/55 px-1.5 py-0.5 text-[10px] font-bold text-white">{item.badge}</span></div><div className="p-3"><h3 className="line-clamp-2 min-h-[38px] text-[14px] font-black leading-snug text-ink">{item.title}</h3><p className="mt-1 line-clamp-1 text-[12px] text-ink-faint">{item.meta}</p></div></Link><button onClick={() => toggleSave(item)} aria-label={`${item.title} ${saved.includes(item.href) ? "보관 취소" : "보관"}`} className={`absolute right-2 top-2 flex h-11 w-11 items-center justify-center rounded-full text-[18px] ${saved.includes(item.href) ? "bg-white text-rose-500" : "bg-black/35 text-white"}`}>{saved.includes(item.href) ? "♥" : "♡"}</button></article>)}</div>; }
