'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import type {TossProduct} from '@/lib/sharelink';
import {affiliateTrack} from '@/lib/affiliate-track';
import styles from './HomeAffiliateShowcase.module.css';
type Slide={id:string;label:string;provider:'toss'|'waug'|'stay';theme:string;eyebrow:string;title:string;description:string;cta:string;url:string;disclosure:string;product?:TossProduct};
const tossDisclosure='[광고] 토스쇼핑 쉐어링크 활동으로, 링크 구매 시 수수료를 지급받습니다.';
const labels:Record<string,string>={meat:'캠핑 고기',water:'생수',cola:'코카콜라',rice:'햇반',ramen:'컵라면',sundae:'순대·내장','camp-food':'캠핑 먹거리','daily-food':'간편식',snack:'두유·음료',travel:'생활 준비물'};
const themes:Record<string,string>={meat:'meat',water:'water',cola:'cola',rice:'rice',ramen:'ramen',sundae:'sundae',snack:'drink',travel:'everyday','camp-food':'meat','daily-food':'drink'};
const art:Record<string,string>={meat:'camp-meat-v3',water:'camp-water-v3',rice:'camp-rice-v3',ramen:'ramen-galaxy-v3',sundae:'camp-sundae-v3',snack:'camp-drink-v3',cola:'weekend-cola-v2'};
const campaignTitles:Record<number,string>={2584893075:'별 보러 갔다가, 한 젓가락 더',1179530071:'캠핑의 클라이맥스, 고기 한 판',135279271:'고기 옆 한 공기, 밥심으로 채워요',2643055003:'집에서도 밖에서도, 시원한 한 병',296698859:'바쁜 아침에도, 한 팩은 챙겨요'};
export default function HomeAffiliateShowcase({products,checkedAt,compact=false,initialIndex=0,collection='camp'}:{products:TossProduct[];checkedAt:string;compact?:boolean;initialIndex?:number;collection?:'camp'|'daily'|'travel'}){
 const [index,setIndex]=useState(initialIndex),[paused,setPaused]=useState(false),[hover,setHover]=useState(false),[visible,setVisible]=useState(false),[reduced,setReduced]=useState(true),[saved,setSaved]=useState<number[]>([]),[message,setMessage]=useState(''),[ticketActive,setTicketActive]=useState(false);
 const hero=useRef<HTMLElement>(null),rail=useRef<HTMLDivElement>(null),seen=useRef(new Set<string>()),drag=useRef({x:0,left:0,active:false,moved:false}),swipe=useRef(0);
 const slides=useMemo(()=>{
  const result:Slide[]=[];
  const topics=collection==='camp'?['camp-food','meat','ramen','rice','sundae']:collection==='daily'?['daily-food','cola','water','snack','travel']:[];
  for(const topic of topics){for(const p of products.filter(p=>p.topic===topic)){const label=p.topic==='camp-food'?(/토시살|안창살|소고기/.test(p.name)?'소고기':/삼겹살|돼지/.test(p.name)?'돼지고기':'핫바·간식'):p.topic==='daily-food'?(/우유/.test(p.name)?'우유':/식빵/.test(p.name)?'식빵':'간편식'):p.id===288570013?'삼겹살':p.id===9133579?'편육':labels[topic];result.push({id:String(p.id),label,provider:'toss',theme:themes[topic],eyebrow:p.endAt?'오늘의 하루특가 SALE':(p.discountRate||0)>0?'토스 할인 SALE':'토스 여행 준비',title:campaignTitles[p.id]||p.headline,description:p.option||p.name,cta:'토스에서 상품 보기',url:p.links.home,disclosure:tossDisclosure,product:p});}}
  if(collection==='travel'){
   if(ticketActive)result.push({id:'ticket',label:'와그 입장권',provider:'waug',theme:'ticket',eyebrow:'포천 · 허브아일랜드',title:'주말 나들이, 입장권부터 가볍게',description:'방문할 날짜와 입장권 옵션을 와그에서 확인하세요.',cta:'와그 입장권 보기',url:'https://www.waug.com/r/99PBHMQK',disclosure:'[광고] 와그 제휴 링크를 통한 구매 시 수수료를 지급받습니다.'});
   result.push({id:'stay',label:'세시간전 숙소',provider:'stay',theme:'stay',eyebrow:'국내 호텔 · 세시간전 제휴',title:'하루 더 머물고 싶은 주말',description:'여기어때 호텔 기획전에서 날짜·지역별 숙소를 살펴보세요.',cta:'숙소 기획전 보기',url:'https://3ha.in/r/722026',disclosure:'[광고] 세시간전 제휴 링크를 통한 숙소 예약 시 수수료를 지급받습니다.'});
  }return result;
 },[products,ticketActive,collection]);
 const active=slides[index%slides.length];
 useEffect(()=>{for(const topic of new Set(products.map(p=>p.topic))){if(art[topic]){const image=new Image();image.src=`/affiliate-images/${art[topic]}.webp`;}}},[products]);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReduced(q.matches);change();q.addEventListener('change',change);setTicketActive(new Date().toISOString()<='2026-12-31T14:59:59.999Z');try{const value=JSON.parse(localStorage.getItem('mwohaji-toss-saved')||'[]');setSaved(Array.isArray(value)?value.filter(Number.isInteger).slice(0,100):[]);}catch{}return()=>q.removeEventListener('change',change);},[]);
 useEffect(()=>{if(!hero.current)return;const observer=new IntersectionObserver(e=>setVisible(e.some(e=>e.isIntersecting)),{threshold:0.35});observer.observe(hero.current);return()=>observer.disconnect();},[slides.length]);
 useEffect(()=>{if(paused||hover||reduced||!visible||slides.length<2)return;const timer=setInterval(()=>{if(!document.hidden)setIndex(i=>(i+1)%slides.length);},1500);return()=>clearInterval(timer);},[paused,hover,reduced,visible,slides.length]);
 useEffect(()=>{if(!visible||!active)return;const key=active.provider+':'+(active.product?.id||active.id);if(!seen.current.has(key)){affiliateTrack('affiliate_impression',active.provider,compact?'home_'+collection:'top','/',active.product?.id);seen.current.add(key);}},[visible,active,compact,collection]);
 useEffect(()=>{if(!rail.current)return;const observer=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;const id=Number((e.target as HTMLElement).dataset.product),key='toss:'+id;if(!seen.current.has(key)){affiliateTrack('affiliate_impression','toss','top','/',id);seen.current.add(key);}}},{threshold:0.5});for(const node of rail.current.querySelectorAll('[data-product]'))observer.observe(node);return()=>observer.disconnect();},[products]);
 const choose=(i:number)=>setIndex((i+slides.length)%slides.length);
 const click=(provider:string,id?:number)=>affiliateTrack('affiliate_click',provider,'top','/',id);
 function save(p:TossProduct){try{const current=JSON.parse(localStorage.getItem('mwohaji-toss-saved')||'[]'),old=Array.isArray(current)?current.filter(Number.isInteger):[];const next=old.includes(p.id)?old.filter(id=>id!==p.id):[p.id,...old].slice(0,100);localStorage.setItem('mwohaji-toss-saved',JSON.stringify(next));setSaved(next);setMessage(next.includes(p.id)?'이 브라우저에 저장했습니다. 가격·재고를 예약하지는 않습니다.':'저장을 해제했습니다.');affiliateTrack('affiliate_save','toss','top','/',p.id);}catch{setMessage('이 브라우저에서는 저장할 수 없습니다.');}}
 if(!active)return null;
 const checked=checkedAt&&Number.isFinite(Date.parse(checkedAt))?new Date(checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'';
 return <section className={`${styles.wrap} ${compact?styles.compact:''}`} aria-label={compact?'여행 중간 기획전':'주말 쇼핑과 여행 혜택'}>
  {compact&&<h3 className={styles.collectionTitle}>{collection==='daily'?'집에서도 가볍게 · 음료·간편식 하루특가':'나들이 예약 · 입장권과 숙소'}</h3>}
  <section ref={hero} aria-roledescription="캐러셀" aria-label="주말 기획전" className={`${styles.hero} ${active.provider==='stay'?styles.posterHero:''} ${styles[active.theme]} ${active.product&&art[active.product.topic]&&active.product.id!==9133579?styles.withArt:''}`} onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocusCapture={()=>setHover(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setHover(false);}} onTouchStart={e=>{swipe.current=e.touches[0].clientX;}} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-swipe.current;if(Math.abs(d)>60){e.preventDefault();choose(index+(d<0?1:-1));}}}>
   {active.provider==='stay'?<a className={styles.posterLink} href={active.url} target="_blank" rel="sponsored noopener noreferrer" aria-label="내 여행 날짜에 맞는 숙소 기획전 보기" onClick={()=>click('stay')}><picture><source media="(max-width:640px)" srcSet="/affiliate-images/stay-poster-mobile-v4.svg"/><img src="/affiliate-images/stay-poster-v4.svg" alt="하루 더 쉬어갈까요? 내 여행 날짜에 맞는 숙소 둘러보기 · 숙소 기획전 보기" width={2100} height={300}/></picture></a>:<div className={styles.stage} key={active.id}>
    <div className={styles.copy}><span className={styles.eyebrow}>{active.eyebrow}</span><h2><a href={active.url} target="_blank" rel="sponsored noopener noreferrer" onClick={()=>click(active.provider,active.product?.id)}>{active.title}</a></h2><p>{active.description}</p>
     {active.product&&<div className={styles.price}>{(active.product.discountRate||0)>0&&<span>{active.product.discountRate}%</span>}<strong>{active.product.price.toLocaleString('ko-KR')}<small>원</small></strong><em>확인한 표시 가격</em></div>}
     {active.product?.endAt&&<p className={styles.end}>하루특가 · {new Date(active.product.endAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})} 종료 예정</p>}
     <a href={active.url} target="_blank" rel="sponsored noopener noreferrer" className={styles.cta} onClick={()=>click(active.provider,active.product?.id)}>{active.cta} <span aria-hidden="true">↗</span></a>
    </div>
    <div className={styles.visual}><a href={active.url} target="_blank" rel="sponsored noopener noreferrer" onClick={()=>click(active.provider,active.product?.id)} aria-label={`${active.product?.name||active.label} 보기`}>{active.product?<figure className={styles.creative}>
     {art[active.product.topic]&&active.product.id!==9133579&&<img className={styles.campaignArt} src={`/affiliate-images/${art[active.product.topic]}.webp`} alt="AI 광고 연출 · 실제 상품 조리 사진이 아닙니다" draggable={false} width={1400} height={600}/>}
     <div className={art[active.product.topic]&&active.product.id!==9133579?styles.productProof:styles.originalOnly}><img src={active.product.image} alt={active.product.name} draggable={false} width={300} height={300}/></div>
     <figcaption>{active.product.imageNote}</figcaption>
    </figure>:<figure><img className={styles.scenePhoto} src={active.provider==='waug'?'/ticket-images/herb-island-6b87a5714e79.jpg':'/affiliate-images/weekend-stay-v2.webp'} alt={active.provider==='waug'?'허브아일랜드 정원 나들이':'따뜻한 객실 분위기의 AI 연출 이미지'} width={420} height={280}/><figcaption>{active.provider==='waug'?'허브아일랜드 나들이':'AI 연출 · 특정 숙소의 실제 사진이 아닙니다'}</figcaption></figure>}</a></div>
   </div>}
   <div className={styles.menu} aria-label="기획전 선택">{slides.map((s,i)=><button key={s.id} type="button" aria-pressed={active.id===s.id} onClick={()=>choose(i)}>{s.label}<span aria-hidden="true">›</span></button>)}</div>
   <div className={styles.controls}><button type="button" aria-label="이전 기획전" onClick={()=>choose(index-1)}>‹</button><span>{index%slides.length+1} / {slides.length}</span><button type="button" aria-label="다음 기획전" onClick={()=>choose(index+1)}>›</button><button type="button" aria-label={paused?'기획전 자동 재생':'기획전 자동 재생 일시정지'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'▶':'Ⅱ'}</button></div>
  </section>
  <p className={styles.disclosure}>{active.disclosure} {active.product?'가격·옵션·재고는 구매 상세에서 확인하세요.':active.provider==='waug'?'이용기한 2026.12.31 · 최신 이용 조건 확인':'지역·날짜는 이동 후 선택 · 혜택은 숙소별로 다릅니다. AI 연출 · 특정 숙소의 실제 사진이 아닙니다.'} {active.product&&art[active.product.topic]&&'AI 광고 장면은 연출이며, 상품 사진은 판매처 제공 이미지입니다.'}</p>
  {!compact&&products.length>0&&<div className={styles.shopping}><div className={styles.railHeading}><h3>캠핑 먹거리 · 오늘의 하루특가 SALE</h3><div><span>옆으로 넘겨보세요</span><button type="button" aria-label="이전 상품" onClick={()=>rail.current?.scrollBy({left:-420,behavior:reduced?'auto':'smooth'})}>‹</button><button type="button" aria-label="다음 상품" onClick={()=>rail.current?.scrollBy({left:420,behavior:reduced?'auto':'smooth'})}>›</button></div></div>
   <p className={styles.railDisclosure}>{tossDisclosure}</p>
   <div ref={rail} className={styles.rail} tabIndex={0} aria-label="토스 상품 좌우 목록" onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();e.currentTarget.scrollBy({left:e.key==='ArrowRight'?210:-210,behavior:reduced?'auto':'smooth'});}}} onPointerDown={e=>{if(e.pointerType!=='mouse'||e.button!==0)return;drag.current={x:e.clientX,left:e.currentTarget.scrollLeft,active:true,moved:false};}} onPointerMove={e=>{if(!drag.current.active)return;const delta=e.clientX-drag.current.x;if(Math.abs(delta)>8){drag.current.moved=true;e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.scrollLeft=drag.current.left-delta;e.preventDefault();}}} onPointerUp={e=>{drag.current.active=false;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{drag.current.active=false;drag.current.moved=false;}} onClickCapture={e=>{if(drag.current.moved){e.preventDefault();e.stopPropagation();drag.current.moved=false;}}}>
    {products.filter(p=>['camp-food','meat','ramen','rice','sundae'].includes(p.topic)).map(p=><article key={p.id} data-product={p.id} className={styles.card}><a href={p.links.home} target="_blank" rel="sponsored noopener noreferrer" onClick={()=>click('toss',p.id)} draggable={false}><div className={styles.cardImage}><img src={p.image} alt={p.name} draggable={false} width={160} height={160} loading="lazy"/>{p.endAt&&<span>하루특가</span>}</div><h4>{p.name}</h4><p className={styles.option}>{p.option}</p><p className={styles.cardPrice}>{(p.discountRate||0)>0&&<b>{p.discountRate}%</b>}<strong>{p.price.toLocaleString('ko-KR')}원</strong></p><small>{p.imageNote}</small></a><button className={styles.save} type="button" aria-label={`${p.name} ${saved.includes(p.id)?'저장 해제':'저장'}`} aria-pressed={saved.includes(p.id)} onClick={()=>save(p)}>{saved.includes(p.id)?'♥':'♡'}</button></article>)}
   </div><p className={styles.fine}>{checked} 확인 · 할인율은 토스 표시 기준 · 가격·옵션·재고는 달라질 수 있습니다.</p><p role="status" className={styles.fine}>{message}</p></div>}
 </section>;
}
