'use client';
import {useRef,useState} from 'react';
import type {PrepStore,PrepProduct,PrepArticle as Article} from '@/lib/weekend-prep/types';
import {PREP_CATEGORIES} from '@/lib/weekend-prep/types';
import PrepArticle from './PrepArticle';
import PrepImageEditor from './PrepImageEditor';
const blank:PrepProduct={id:'',name:'',affiliateUrl:'',image:'',source:'',checkedAt:'',specification:'',options:'',verified:false,evidence:''};
export default function PrepAdmin(){
 const [token,setToken]=useState(''),[store,setStore]=useState<PrepStore|null>(null),[message,setMessage]=useState(''),[product,setProduct]=useState<PrepProduct>(blank),[selected,setSelected]=useState(''),[preview,setPreview]=useState(false),[candidate,setCandidate]=useState<Partial<PrepProduct>|null>(null);
 const article=store?.articles.find(a=>a.slug===selected);
 const pending=useRef(false);
 async function request(body?:unknown){const r=await fetch('/api/weekend-prep/admin',{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
 async function run(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;try{setMessage('처리 중…');await fn();}catch(e){setMessage(e instanceof Error?e.message:'작업 실패');}finally{pending.current=false;}}
 function edit(patch:Partial<Article>){if(store&&article)setStore({...store,articles:store.articles.map(a=>a.slug===selected?{...a,...patch}:a)});}
 return <div className="prep-admin"><p className="prep-notice">관리는 로컬 개발 서버에서만 가능합니다. 저장은 비공개 초안이며, 공개·예약 상태로 저장한 내용은 배포 후 반영됩니다.</p><label>관리자 토큰<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><button className="prep-action" onClick={()=>run(async()=>{const s=await request();setStore(s);setSelected(s.articles[0]?.slug||'');setMessage('불러왔습니다.');})}>작업 불러오기</button><p role="status">{message}</p>{store&&<>
 <fieldset><legend>1. 상품 등록 · 원본 링크 보존</legend><select aria-label="등록 상품 선택" value={product.id} onChange={e=>setProduct(store.products.find(p=>p.id===e.target.value)||blank)}><option value="">새 상품</option>{store.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{(['id','name','affiliateUrl','image','specification','options','source','checkedAt','evidence'] as const).map((key,i)=><label key={key}>{['상품 ID','상품명','원본 제휴링크','사진 URL (수동 입력 가능)','규격','선택 옵션','정보 출처','확인 시각 (ISO)','대조 근거·선택 이유·주의점'][i]}<input value={product[key]} onChange={e=>setProduct({...product,[key]:e.target.value,verified:false})}/></label>)}<button className="prep-action" onClick={()=>run(async()=>{const d=await request({action:'lookup',name:product.name,affiliateUrl:product.affiliateUrl});setCandidate(d.candidate);setMessage(d.message);})}>API / 캐시에서 후보 조회</button>{candidate&&<div><p>조회 후보: {candidate.name}</p>{candidate.image&&<img src={candidate.image} alt="조회 후보 상품 사진" width={200} height={200} referrerPolicy="no-referrer"/>}<button onClick={()=>setProduct({...product,id:product.id||candidate.id||'',image:candidate.image||'',source:candidate.source||'',checkedAt:candidate.checkedAt||'',verified:false})}>후보 정보를 입력란에 복사</button><p>자동 일치 승인이 아닙니다. 규격과 옵션은 직접 확인하세요.</p></div>}<label><input type="checkbox" checked={product.verified} onChange={e=>setProduct({...product,verified:e.target.checked})}/>상품명·사진·규격·옵션과 원본 링크의 동일 상품을 확인했습니다.</label><button className="prep-action" onClick={()=>{if(!product.id||!product.name)return setMessage('상품 ID와 이름을 입력하세요.');setStore({...store,products:[...store.products.filter(p=>p.id!==product.id),product]});setMessage('작업에 추가했습니다. 아래 저장 버튼으로 보관하세요.');}}>상품을 작업에 추가</button></fieldset>
 <fieldset><legend>2. 주제와 초안</legend><select aria-label="편집할 글" value={selected} onChange={e=>{setSelected(e.target.value);setPreview(false);}}>{store.articles.map(a=><option key={a.slug} value={a.slug}>{a.title}</option>)}</select><button onClick={()=>{const slug='draft-'+Date.now();const a:Article={slug,title:'새 주말 이야기',description:'독자가 얻을 수 있는 도움을 적어 주세요.',category:'피크닉·나들이',status:'draft',publishAt:'',updatedAt:new Date().toISOString(),reviewed:false,cover:{url:'',alt:'',width:1200,height:800,generated:true,reviewed:false,tags:[]},sections:[{heading:'어떤 주말을 준비하나요?',text:'',productIds:[]}],productIds:[],internalLinks:[]};setStore({...store,articles:[...store.articles,a]});setSelected(slug);}}>새 글 시작</button>{article&&<><label>제목<input value={article.title} onChange={e=>edit({title:e.target.value,reviewed:false})}/></label><label>짧은 설명<input value={article.description} onChange={e=>edit({description:e.target.value,reviewed:false})}/></label><label>분류<select value={article.category} onChange={e=>edit({category:e.target.value as Article['category']})}>{PREP_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>run(async()=>{const d=await request({action:'draft',title:article.title,category:article.category,productIds:article.productIds});edit({description:d.description,sections:d.sections,reviewed:false,status:'draft'});setMessage('초안을 생성했습니다. 내용과 상품 연결을 검토하세요.');})}>등록 상품으로 초안 생성 (저장된 상품 사용)</button><p>필요한 상품을 선택하세요. 본문에 상품명을 넣으면 처음 한 번 링크로 연결됩니다.</p>{store.products.map(p=><label key={p.id}><input type="checkbox" checked={article.productIds.includes(p.id)} onChange={e=>edit({productIds:e.target.checked?[...article.productIds,p.id]:article.productIds.filter(id=>id!==p.id),reviewed:false})}/>{p.name}</label>)}{article.sections.map((s,i)=><div key={i}><label>소제목<input value={s.heading} onChange={e=>edit({sections:article.sections.map((v,j)=>i===j?{...v,heading:e.target.value}:v),reviewed:false})}/></label><label>본문<textarea value={s.text} onChange={e=>edit({sections:article.sections.map((v,j)=>i===j?{...v,text:e.target.value,productIds:article.productIds}:v),reviewed:false})}/></label><button onClick={()=>edit({sections:article.sections.filter((_,j)=>j!==i),reviewed:false})}>단락 삭제</button></div>)}<button onClick={()=>edit({sections:[...article.sections,{heading:'',text:'',productIds:article.productIds}],reviewed:false})}>단락 추가</button></>}</fieldset>
 {article&&<><fieldset><legend>본문 이미지 · 생성과 태그 편집</legend><p>필요한 단락에만 이미지를 연결하세요. 불필요한 반복 이미지는 넣지 않습니다.</p><h2>대표 이미지 생성</h2><PrepImageEditor photo={article.cover} products={store.products.filter(p=>article.productIds.includes(p.id))} onChange={cover=>edit({cover})} onGenerate={headline=>run(async()=>{const d=await request({action:'image',slug:article.slug,slot:'cover',prompt:article.cover.prompt||article.cover.alt,headline});edit({cover:d.image});setMessage('이미지 생성 완료. 한글 문구와 외형을 검토하세요.');})}/>{article.sections.map((s,i)=><div key={i}><h2>{s.heading}</h2>{s.image?<><PrepImageEditor photo={s.image} products={store.products.filter(p=>article.productIds.includes(p.id))} onChange={image=>edit({sections:article.sections.map((v,j)=>j===i?{...v,image}:v)})} onGenerate={headline=>run(async()=>{const d=await request({action:'image',slug:article.slug,slot:'body-'+i,prompt:s.image?.prompt||s.image?.alt,headline});edit({sections:article.sections.map((v,j)=>j===i?{...v,image:d.image}:v)});setMessage('본문 이미지 생성 완료. 검토 후 저장하세요.');})}/><button onClick={()=>edit({sections:article.sections.map((v,j)=>j===i?{...v,image:undefined}:v)})}>본문 이미지 빼기</button></>:<button onClick={()=>edit({sections:article.sections.map((v,j)=>j===i?{...v,image:{url:'',alt:'',prompt:'',width:1200,height:800,generated:true,reviewed:false,tags:[]}}:v)})}>이 단락에 설명 이미지 추가</button>}</div>)}</fieldset><fieldset><legend>4. 검토와 발행</legend><label><input type="checkbox" checked={article.reviewed} onChange={e=>edit({reviewed:e.target.checked})}/>본문의 고유성·사실·상품 연결을 검토했습니다.</label><label>상태<select value={article.status} onChange={e=>edit({status:e.target.value as Article['status'],publishAt:article.publishAt||new Date().toISOString()})}><option value="draft">비공개 초안</option><option value="scheduled">예약 발행</option><option value="published">발행</option></select></label><label>발행 시각 (시간대 포함 ISO, 한국 +09:00)<input value={article.publishAt} onChange={e=>edit({publishAt:e.target.value})}/></label><button onClick={()=>setPreview(!preview)}>미리보기 {preview?'닫기':'열기'}</button><button className="prep-action" onClick={()=>run(async()=>{const s=await request({action:'save',store,version:store.version});setStore(s);setMessage('저장 완료. 공개·예약 내용은 배포 후 반영됩니다.');})}>검사 후 저장</button></fieldset>{preview&&<PrepArticle article={article} products={store.products} preview/>}</>}
 </>}</div>;
}
