import type {Metadata} from 'next';
import Link from 'next/link';
import NextImage, {type ImageProps} from 'next/image';
function Image(props:ImageProps){return props.src?<NextImage {...props}/>:<div className="prep-no-image">이미지 검토 대기 · 비공개 초안</div>;}
import {COOKING_CATEGORIES,cookingCategory,getPrepArticles,isCookingPrepArticle,isPrepReview,prepCategoryLabel} from '@/lib/weekend-prep/data';
import {PREP_CATEGORIES} from '@/lib/weekend-prep/types';
import {SITE} from '@/lib/site';
import './prep.css';
type Props={searchParams:Promise<{q?:string;category?:string;cooking?:string;page?:string}>};
export async function generateMetadata({searchParams}:Props):Promise<Metadata>{const p=await searchParams;return {title:'주말 준비물 체크리스트 | 요리·캠핑·나들이 준비',description:'요리·캠핑용품·야외 놀이·여행 준비물을 주제별로 확인하고, 출발 전에 필요한 항목을 체크하세요.',alternates:{canonical:`${SITE.url}/weekend-prep`},robots:{index:!isPrepReview&&!Object.keys(p).length&&getPrepArticles().length>0,follow:true}};}
export default async function Page({searchParams}:Props){const p=await searchParams;const all=getPrepArticles();const q=String(p.q||'').slice(0,100);const category=String(p.category||'');const cooking=COOKING_CATEGORIES.includes(p.cooking as never)?p.cooking as typeof COOKING_CATEGORIES[number]:'';const list=all.filter(a=>(!category||prepCategoryLabel(a.category,a)===category)&&(!cooking||isCookingPrepArticle(a)&&cookingCategory(a)===cooking)&&`${a.title} ${a.description}`.includes(q));const pages=Math.max(1,Math.ceil(list.length/9));const page=Math.min(pages,Math.max(1,parseInt(p.page||'1')||1));const href=(nextCategory:string,n=1,nextCooking='')=>{const s=new URLSearchParams();if(q)s.set('q',q);if(nextCategory)s.set('category',nextCategory);if(nextCategory==='캠핑요리 준비하기'&&nextCooking)s.set('cooking',nextCooking);if(n>1)s.set('page',String(n));return '/weekend-prep'+(s.size?'?'+s:'');};return <main className="prep">{isPrepReview&&<p className="prep-notice">로컬 검토 화면 · 비공개 초안이 포함되어 있습니다.</p>}<p className="prep-eyebrow">WEEKEND GUIDE</p><h1>주말 준비물 체크리스트</h1><p className="prep-lead">이번 주말에 필요한 준비물을 주제별로 확인하세요.<br/>요리·캠핑용품·나들이 준비를 한곳에서 체크할 수 있어요.</p><form className="prep-search"><input name="q" defaultValue={q} aria-label="주말 준비물 검색" placeholder="어떤 준비물이 필요하세요?"/>{category&&<input type="hidden" name="category" value={category}/>}<button>검색</button></form><nav className="prep-filters" aria-label="준비물 분류"><Link href={href('')} aria-current={!category?'page':undefined}>전체 보기</Link>{PREP_CATEGORIES.filter(c=>all.some(a=>prepCategoryLabel(a.category,a)===c)).map(c=><Link key={c} href={href(c)} aria-current={category===c?'page':undefined}>{c}</Link>)}</nav>{category==='캠핑요리 준비하기'&&<nav className="prep-filters" aria-label="캠핑요리 종류">{COOKING_CATEGORIES.map(c=><Link key={c} href={href(category,1,c)} aria-current={cooking===c?'page':undefined}>{c}</Link>)}</nav>}{!list.length?<div className="prep-empty">{all.length?'검색 결과가 없어요. 다른 단어로 찾아보세요.':'알찬 주말 준비 이야기를 준비하고 있어요.'}<p><Link href="/camping">캠핑 장소 둘러보기 →</Link></p></div>:<div className="prep-grid">{list.slice((page-1)*9,page*9).map(a=><Link className="prep-card" href={`/weekend-prep/${a.slug}`} key={a.slug}><Image src={a.cover.url} alt={a.cover.alt} width={a.cover.width} height={a.cover.height} sizes="(max-width:480px) 100vw,(max-width:760px) 50vw,360px"/><div className="prep-card-copy"><span className="prep-eyebrow">{prepCategoryLabel(a.category,a)}{isCookingPrepArticle(a)&&<small> · {cookingCategory(a)}</small>}</span><h2>{a.title}</h2><p>{a.description}</p></div></Link>)}</div>}{pages>1&&<nav aria-label="페이지" className="prep-pages">{Array.from({length:pages},(_,i)=><Link key={i} aria-current={page===i+1?'page':undefined} href={href(category,i+1,cooking)}>{i+1}</Link>)}</nav>}</main>;}
