import type {Metadata} from 'next';
import Link from 'next/link';
import NextImage, {type ImageProps} from 'next/image';
function Image(props:ImageProps){return props.src?<NextImage {...props}/>:<div className="prep-no-image">이미지 검토 대기 · 비공개 초안</div>;}
import {getPrepArticles,isPrepReview} from '@/lib/weekend-prep/data';
import {PREP_CATEGORIES} from '@/lib/weekend-prep/types';
import {SITE} from '@/lib/site';
import './prep.css';
type Props={searchParams:Promise<{q?:string;category?:string;page?:string}>};
export async function generateMetadata({searchParams}:Props):Promise<Metadata>{const p=await searchParams;return {title:'주말 준비물 | 주말에 뭐하지?',description:'캠핑 먹거리부터 아이와 놀이, 피크닉과 여행까지. 주말을 가볍게 준비하는 방법을 만나보세요.',alternates:{canonical:`${SITE.url}/weekend-prep`},robots:{index:!isPrepReview&&!Object.keys(p).length&&getPrepArticles().length>0,follow:true}};}
export default async function Page({searchParams}:Props){const p=await searchParams;const all=getPrepArticles();const q=String(p.q||'').slice(0,100);const list=all.filter(a=>(!p.category||a.category===p.category)&&`${a.title} ${a.description}`.includes(q));const pages=Math.max(1,Math.ceil(list.length/9));const page=Math.min(pages,Math.max(1,parseInt(p.page||'1')||1));const href=(category:string,n=1)=>{const s=new URLSearchParams();if(q)s.set('q',q);if(category)s.set('category',category);if(n>1)s.set('page',String(n));return '/weekend-prep'+(s.size?'?'+s:'');};return <main className="prep">{isPrepReview&&<p className="prep-notice">로컬 검토 화면 · 비공개 초안이 포함되어 있습니다.</p>}<p className="prep-eyebrow">WEEKEND NOTES</p><h1>주말 준비물</h1><p className="prep-lead">한 글에는 한 가지 주말의 즐길 거리를 담았습니다.<br/>필요한 보조 준비물은 사진 속 +에서만 가볍게 확인하세요.</p><form className="prep-search"><input name="q" defaultValue={q} aria-label="주말 준비물 글 검색" placeholder="어떤 주말을 준비하고 있나요?"/>{p.category&&<input type="hidden" name="category" value={p.category}/>}<button>검색</button></form><nav className="prep-filters" aria-label="준비물 분류"><Link href={href('')} aria-current={!p.category?'page':undefined}>전체 보기</Link>{PREP_CATEGORIES.filter(c=>all.some(a=>a.category===c)).map(c=><Link key={c} href={href(c)} aria-current={p.category===c?'page':undefined}>{c}</Link>)}</nav>{!list.length?<div className="prep-empty">{all.length?'검색 결과가 없어요. 다른 단어로 찾아보세요.':'알찬 주말 준비 이야기를 준비하고 있어요.'}<p><Link href="/camping">캠핑 장소 둘러보기 →</Link></p></div>:<div className="prep-grid">{list.slice((page-1)*9,page*9).map(a=><Link className="prep-card" href={`/weekend-prep/${a.slug}`} key={a.slug}><Image src={a.cover.url} alt={a.cover.alt} width={a.cover.width} height={a.cover.height} sizes="(max-width:480px) 100vw,(max-width:760px) 50vw,360px"/><div className="prep-card-copy"><span className="prep-eyebrow">{a.category}</span><h2>{a.title}</h2><p>{a.description}</p></div></Link>)}</div>}{pages>1&&<nav aria-label="페이지" className="prep-pages">{Array.from({length:pages},(_,i)=><Link key={i} aria-current={page===i+1?'page':undefined} href={href(p.category||'',i+1)}>{i+1}</Link>)}</nav>}</main>;}
