const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const modules=new Map();
function load(file){file=path.resolve(file);if(!path.extname(file))file+=['.ts','.tsx','.js'].find(ext=>fs.existsSync(file+ext))||'.ts';if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(modules.has(file))return modules.get(file).exports;const m={exports:{}};modules.set(file,m);const local=name=>name==='server-only'?{}:name.startsWith('@/')?load(name.slice(2)):name.startsWith('.')?load(path.resolve(path.dirname(file),name)):require(name);new Function('exports','module','require',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText)(m.exports,m,local);return m.exports;}
const {eventOffer}=load('lib/eventSeo');
const {classifyEvent}=load('lib/price.js');
assert.equal(classifyEvent({priceRaw:'',genreKey:'festival',title:'가을 축제',place:'시청 광장'}).type,'unknown');
assert.equal(classifyEvent({priceRaw:'무료'}).type,'free');
assert.equal(classifyEvent({priceRaw:'어린이 무료, 성인 10,000원'}).type,'partial_free');
for(const file of ['data/events.json','data/events-archive.json']){
  const events=load(file).events;
  const allowedPrices=new Set(['free','partial_free','cheap','paid','unknown']);
  assert(events.every(e=>allowedPrices.has(e.priceType)),file+' has an unrecognized price classification');
  assert(events.filter(e=>e.priceType==='unknown').every(e=>e.priceLabel==='요금 정보 확인 필요'),file+' unknown label');
}
assert.equal(eventOffer({priceType:'free',priceMin:0,priceMax:0}).price,0);
assert.equal(eventOffer({priceType:'paid',priceMin:10000,priceMax:10000}).price,10000);
for(const priceType of ['partial_free','unknown'])assert.equal(eventOffer({priceType,priceMin:0,priceMax:10000}),undefined);
assert.equal(eventOffer({priceType:'paid',priceMin:10000,priceMax:20000}),undefined);
assert(!('availability' in eventOffer({priceType:'free',priceMin:0,priceMax:0})));
const sitemap=load('app/sitemap').default(),urls=sitemap.map(s=>s.url),set=new Set(urls);
assert.equal(urls.length,set.size,'Unique sitemap URLs');
assert(!urls.some(u=>u.includes('/traditional-market')), 'Hidden markets stay out of sitemap');
assert(!urls.some(u=>/\/tickets(?:\/|$)|\/kids\/c\/|\/near(?:\/|$)|\/game(?:\/|$)/.test(u)), 'Redirected and thin routes stay out of sitemap');
assert(urls.length<50000,'Single sitemap URL limit');
assert(urls.every(u=>u.startsWith('https://mwohaji.kr')&&!u.includes('?')&&!u.includes('undefined')));
assert(!urls.some(u=>/\/(search|saved|plan|admin)(\/|$)/.test(u)));
for(const p of ['/season','/date','/camping'])assert(set.has('https://mwohaji.kr'+p));
assert(set.has('https://mwohaji.kr/places/spot/2774564'),'Canonical place stays in sitemap');
assert(!set.has('https://mwohaji.kr/places/spot/3353336'),'Duplicate place stays out of sitemap');
assert(!urls.some(u=>/\/date\/|\/camping\/collections(?:\/|$)/.test(u)),'Generated date and camping collections stay out of sitemap');
assert(!urls.some(u=>/\/food\/category\/|\/food\/(?!spot\/)[^/]+\/[^/]+$|\/course\/theme\/|\/course\/(?!c\/)[^/]+\/[^/]+$|\/camping\/type\/|\/region\/[^/]+\/[^/]+$/.test(u)),'Filter combinations stay out of sitemap');
const currentMonth=new Date(Date.now()+9*60*60*1000).getUTCMonth()+1;
assert(!urls.some(u=>{const match=u.match(/\/month\/(\d+)$/);return match&&Number(match[1])<currentMonth;}),'Past month archives stay out of sitemap');
const {getKidCourses}=load('lib/kidCourses'),{getAllBundles}=load('lib/campingCollections');
assert(getKidCourses().every(c=>!set.has('https://mwohaji.kr/kids/c/'+c.id)));
assert(getAllBundles().every(c=>!set.has('https://mwohaji.kr/camping/collections/'+c.slug)));
const {getAllEvents}=load('lib/data'),{hasSubstantiveEventInfo}=load('lib/eventQuality'),{todayYmd}=load('lib/dates');
for(const e of getAllEvents())assert.equal(set.has('https://mwohaji.kr/event/'+e.id),e.endDate>=todayYmd()&&hasSubstantiveEventInfo(e),e.id+' event quality');
const {getAllArticles}=load('lib/articles'),{getAllPlaces}=load('lib/tour');
const {getAllRestaurants}=load('lib/food');
const {hasSubstantivePlaceInfo,hasSubstantiveRestaurantInfo,hasSubstantiveCampInfo}=load('lib/placeQuality');
const live=new Set(getAllPlaces().map(p=>p.id));
for(const a of getAllArticles())if(!live.has(a.id))assert(!set.has('https://mwohaji.kr/places/spot/'+a.id));
for(const p of getAllPlaces())assert.equal(set.has('https://mwohaji.kr/places/spot/'+p.id),hasSubstantivePlaceInfo(p.id),p.id+' place quality');
for(const r of getAllRestaurants())assert.equal(set.has('https://mwohaji.kr/food/spot/'+r.id),hasSubstantiveRestaurantInfo(r.id),r.id+' restaurant quality');
const {getAllCamps}=load('lib/camping');
for(const c of getAllCamps())assert.equal(set.has('https://mwohaji.kr/camping/'+c.id),hasSubstantiveCampInfo(c),c.id+' camp quality');
const robots=load('app/robots').default();
const matches=(rule,url)=>new RegExp('^'+rule.split('*').map(p=>p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('.*')).test(url);
const metaTraining=robots.rules.find(r=>r.userAgent==='Meta-ExternalAgent');
assert(metaTraining&&[metaTraining.disallow||[]].flat().includes('/'),'Meta AI training crawler is blocked');
assert(!robots.rules.some(r=>['Meta-WebIndexer','facebookexternalhit','Meta-ExternalFetcher'].includes(r.userAgent)),'Meta search, previews and user fetchers stay available');
for(const r of robots.rules.filter(r=>r!==metaTraining)){const dis=[r.disallow||[]].flat();for(const url of ['/_next/static/chunks/app.js?dpl=test','/_next/image?url=photo.jpg&w=640&q=75','/search?q=서울','/api/pet-travel?area=서울','/region/seoul','/?utm_source=test'])assert(!dis.some(d=>matches(d,url)),r.userAgent+' can crawl '+url);}
const eventStory=load('lib/eventStory').eventStory;
assert(eventStory({title:'test',realmName:'전시',area:'서울',sigungu:'',place:'',startDate:'20260901',endDate:'20260910',priceLabel:'요금 정보 확인 필요',priceType:'unknown'}).some(s=>s.includes('장소 서울')));
console.log(JSON.stringify({passed:true,sitemapUrls:urls.length,kidCourses:getKidCourses().length,bundles:getAllBundles().length,petDetails:urls.filter(u=>u.includes('/pet-travel/')).length,checks:['confirmed prices','no inferred free admission','sitemap coverage and uniqueness','canonical targets','robots asset and AI search access']}));
