const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const modules=new Map();
function load(file){file=path.resolve(file);if(!path.extname(file))file+=fs.existsSync(file+'.ts')?'.ts':'.js';if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(modules.has(file))return modules.get(file).exports;const m={exports:{}};modules.set(file,m);const local=name=>name.startsWith('@/')?load(name.slice(2)):name.startsWith('.')?load(path.resolve(path.dirname(file),name)):require(name);new Function('exports','module','require',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText)(m.exports,m,local);return m.exports;}
const {regionHub}=load('lib/regionHub.ts'),{SIDO_SLUG}=load('lib/classify');
for(const [area,code] of Object.entries(SIDO_SLUG)){const h=regionHub(area,code);assert(h.sections.every(s=>s.items.length>0));assert(h.recommended.length>=6&&h.recommended.length<=8);assert(new Set(h.recommended.map(p=>p.href)).size===h.recommended.length);assert(new Set(h.recommended.map(p=>p.badge)).size>=2);console.log(JSON.stringify({area,recommended:h.recommended.map(p=>p.badge),sections:Object.fromEntries(h.sections.map(s=>[s.key,s.items.length]))}));}
const {cityTourPhotos,cityTourStops}=load('lib/cityTourPhotos.ts'),{getCityTours}=load('lib/cityTours.ts'),{photoArea,galleryForStops}=load('lib/photoGallery.ts');
assert.equal(galleryForStops([{name:'평화공원',addr:'부산광역시 남구',num:1,overview:'',image:''}],5,'서울').length,0);
for(const a of getCityTours()){const photos=cityTourPhotos(a),stops=cityTourStops(a);assert(photos.length<=5);assert(new Set(photos.map(p=>p.image)).size===photos.length);assert(photos.every(p=>photoArea(p.location)===a.area));console.log(JSON.stringify({city:a.id,area:a.area,count:photos.length,stops:stops.map(s=>s.name),photos:photos.map(p=>({title:p.title,location:p.location}))}));}
console.log('PASS: 17 region hubs, diversified unique recommendations, nonempty sections, exact stop/area matching, unique photo URLs');
